"""
Unit tests for scanner/package_scanner.py

STUB — waiting for Person A (Task 2) to complete the package scanner.
Tests will be filled in once scanner/package_scanner.py exists.
"""

import pytest


@pytest.mark.skip(reason="Waiting for Task 2 (Person A) — package_scanner.py not yet implemented")
class TestRequirementsParser:
    def test_parse_pinned_version(self): ...
    def test_parse_greater_than_equal(self): ...
    def test_parse_no_version(self): ...
    def test_parse_multiple_requirements_files(self): ...
    def test_parse_pyproject_toml_dependencies(self): ...
    def test_parse_pipfile_packages(self): ...


@pytest.mark.skip(reason="Waiting for Task 2 (Person A) — package_scanner.py not yet implemented")
class TestTransitiveDependencyResolution:
    def test_python_slugify_pulls_in_unidecode(self): ...
    def test_transitive_gpl_flagged_as_critical(self): ...
    def test_direct_dep_chain_shown_in_output(self): ...


@pytest.mark.skip(reason="Waiting for Task 2 (Person A) — package_scanner.py not yet implemented")
class TestDepsDotDevApiParsing:
    def test_spdx_license_extracted(self): ...
    def test_fallback_to_pypi_json_on_failure(self): ...
    def test_response_cached_locally(self): ...


@pytest.mark.skip(reason="Waiting for Task 2 (Person A) — package_scanner.py not yet implemented")
class TestAgplSaasDetection:
    def test_ultralytics_plus_fastapi_is_critical(self): ...
    def test_ultralytics_without_saas_is_medium(self): ...
    def test_dockerfile_counts_as_saas_indicator(self): ...
